#!/bin/sh

_fetch_ver="5"
[[ -f "/etc/sabayon-edition" ]] && _fetch_ver=$(cat /etc/sabayon-edition | cut -d" " -f 3)

FETCH_VER=${FETCH_VER:-${_fetch_ver}}
FETCH_FN="anaconda-${FETCH_VER}.tar.bz2"
FETCH_URL=${FETCH_URL:-"http://www.sabayon.org/sabayon/installer/${FETCH_FN}"}

cd /tmp
echo "Fetching Sabayon Anaconda Installer from ${FETCH_URL}..."
wget ${FETCH_WGET_ARGS} "${FETCH_URL}"
if [ "${?}" = "0" ]; then
	tar xjf "${FETCH_FN}" -C /
	echo "ALL FINE, respawn the installer"
	exit 0
else
	echo "OUCH, something bad happened"
	exit 1
fi

