#!/bin/sh

export ANACONDA_PRODUCTNAME="Sabayon"
export ANACONDA_PRODUCTVERSION="$(cat /etc/sabayon-release | cut -d' ' -f 4)"
export ANACONDA_PRODUCTPATH="/mnt/livecd"
export ANACONDA_CHROOTPATH="/mnt/sabayon"
export ANACONDA_PRODUCTARCH="$(cat /etc/sabayon-release | cut -d' ' -f 3)"
export ANACONDA_BUGURL="http://bugs.sabayon.org"

exec anaconda --liveinst
